#生产环境
profiles: pub

app:
  domain: "http://132.232.61.181:59845"

#数据库配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1/panda?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ikyOedVzV4bpXeWl
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      max-wait-millis: 60000
#缓存数据库配置
  redis:
    host: 132.232.61.181
    port: 6379
    password: ikyOedVzV4bpXeWl
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8
    timeout: 60000


#数据库框架配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#服务容器配置
server:
  port: 59845
  tomcat:
    uri-encoding: UTF-8
  address: 0.0.0.0

#日志配置
logging:
  level:
    root: debug
  file: c:boot.log
